
name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test
        run: npm run ng test --sourceMap=false --browsers=ChromeHeadless --watch=false
